MAIN
	MOVE TEMP 2 Add_Vtable
	MOVE TEMP 3 HALLOCATE 4
	HSTORE TEMP 2 0 TEMP 3
	MOVE TEMP 4 Add_Main
	HSTORE TEMP 3 0 TEMP 4
 
	MOVE TEMP 5 12
	MOVE TEMP 6 21
	MOVE TEMP 7 PLUS TEMP 5 TEMP 6
	PRINT TEMP 7
END

